name: Deploy SEBRAE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v3

      - name: Buildar imagem Docker
        run: docker build -t sistema-sebrae .

      - name: Confirmar build
        run: echo "Imagem buildada com sucesso!"